config/routes.rb
Rails.application.routes.draw do

  #get 'payments/create'
  resources :attachments, only: [:create, :destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create, :destroy]
  devise_for :users

  get 'email/create'
 # post 'emails/create', as: :create_email
 post "/pagar", to: "payments#create"

  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id", as: :add_to_cart, to: "in_shopping_carts#create"
  get "/checkout", to: "payments#checkout"

  post "email/create", as: :create_email
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end
end

app/views/partials/_nav.haml
%header
  %nav.green
    %ul.no-list.no-padding.text-center
      %li.col-md-4.inline-block.tall-padding.white-text
        -if user_signed_in?
          =link_to root_path, class:"right-space white-text" do
            %i.mdi-action-shopping-basket
            MI tienda
          =link_to "", class:"right-space white-text" do
            %i.mdi-action-trending-up
            Ordenems
          =link_to "", class:"right-space white-text" do
            %i.mdi-action-alarm
            Descuentos
      %li.col-md-4.inline-block.text-center.tall-padding
        =image_tag "logoch.png",height:"25px"
      %li.col-md-4.inline-block.tall-padding
        =link_to carrito_path, class:"white-text" do
          %i.mdi-action-shopping-cart
          Mi carrito
          (
          = @shopping_cart.products.size
          )