config/routes.rb
Rails.application.routes.draw do

  #get 'payments/create'
  resources :attachments, only: [:create, :destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create, :destroy]
  devise_for :users

  get 'email/create'
 # post 'emails/create', as: :create_email
 post "/pagar", to: "payments#create"

  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id", as: :add_to_cart, to: "in_shopping_carts#create"
  get "/checkout", to: "payments#checkout"

  post "email/create", as: :create_email
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def unregistered
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.haml
%h1 bienvenido

%p
  =link_to "iniciar sesion", new_user_session_path

%p
  =link_to "crear cuenta", new_user_registration_path

app/views/welcome/unregistered.haml
%header.green.big-padding
  .col-md-10.no-float.center-block
    .col-md-6.no-padding.inline-block
      =image_tag "TiMedi.png",width:"100"
      %h1.white-text.utra-big.kostic
        %strong
        Ofrese Tus Productos Digitales
    .col-md-5.inline-block
      =image_tag "men.png"
.grey.white-text.big-padding.kostic
  .col-md-10.no-float.center-block
    .absolute{style:"bottom:-4.5em;width:100%;left:0px;"}
      .text-center.big
        .col-md-3.inline-block
          .white.grey-text.circle
            %strong 1
        .col-md-3.inline-block
          .white.grey-text.circle
            %strong 2
        .col-md-3.inline-block
          .white.grey-text.circle
            %strong 3
    %h2.bigger.kostic.text-center
      %strong Tienda en 3 pasos
    %div.text-center.top-space
      .col-md-3.inline-block.text-left
        =image_tag "cloud.png", class:"col-md-10 inline-block"
        .top-space
        %strong.medium
          sube tus archivos a Timul
        %p.white-text.text-ustify.small
          Lorem ipsum dolor sit amet consectetur
          Autem facilis aspernatur, dolor at,
          possimus culpa qui voluptas praesentium
      .col-md-3.inline-block.text-left
        =image_tag "media.png", class:"col-md-10 inline-block"
        .top-space
        %strong.medium
          sube tus archivos a Timul
        %p.white-text.text-ustify.small
          Lorem ipsum dolor sit amet consect
          Autem facilis aspernatur, dolor at
          possimus culpa qui voluptas praese
      .col-md-3.inline-block.text-left
        =image_tag "money.png", class:"col-md-10 inline-block"
        .top-space
        %strong.medium
          sube tus archivos a Timul
        %p.white-text.text-ustify.small
          Lorem ipsum dolor sit amet consectetur
          Autem facilis aspernatur, dolor at,
          possimus culpa qui voluptas praesentium
.red.white-text.big-padding.kistic{style:"margin-top:5em;"}
  .col-md-8.no-float.text-center.center-block
    =image_tag "files.png"
    %p.medium.col-md-11.center-block.no-float.top-space
      %strong
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Eaque debitis nisi doloribus nemo ut dolo remque aut non,
        esse deleniti perspiciatis, autem neque natus dolore?
.top-space.big-padding.bottom-space
  .col-md-11.col-xs-12.center-block.no-float
    =form_tag(create_email_path,method: :post, remote:true, id: "email-form") do
      =email_field_tag "email",nil,class:"col-xs-12 inline-block text-center landing-form",placeholder:"Escribhe aqui tu email"
    #email-info.red.white-text.large-padding